# Generated by Django 2.1.7 on 2019-03-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20190314_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
