# Generated by Django 2.1.7 on 2019-04-06 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_auto_20190318_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=6)),
                ('class_name', models.CharField(max_length=8)),
                ('people', models.CharField(max_length=8)),
                ('year', models.CharField(max_length=6)),
                ('hebanhao', models.CharField(max_length=6, verbose_name='合班号')),
                ('zhuanyehao', models.CharField(max_length=6, verbose_name='专业号')),
            ],
            options={
                'verbose_name_plural': '班级表',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classRoom_id', models.CharField(max_length=6, verbose_name='教室号')),
                ('classRoom_name', models.CharField(max_length=20, verbose_name='教室名')),
                ('rongliang', models.CharField(max_length=8, verbose_name='容量 ')),
                ('didian', models.CharField(max_length=8, verbose_name='地点')),
                ('leixing', models.CharField(max_length=10, verbose_name='类型')),
                ('shi_yong_qing_kuang', models.CharField(max_length=6, verbose_name='使用情况')),
            ],
            options={
                'verbose_name_plural': '教室名',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_id', models.CharField(max_length=6)),
                ('course_for_major', models.CharField(max_length=20)),
                ('course_times', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name_plural': '课程表',
            },
        ),
        migrations.CreateModel(
            name='jiaoxue_task_book_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_hao', models.CharField(max_length=6, verbose_name='教师号')),
                ('xueyuan', models.CharField(max_length=28, verbose_name='学院')),
                ('jiaoyanshi', models.CharField(max_length=10, verbose_name='教研室')),
                ('class_id', models.CharField(max_length=10, verbose_name='班级号')),
                ('zhuanye_hao', models.CharField(max_length=10, verbose_name='专业号')),
                ('heban_hao', models.CharField(max_length=6, verbose_name='合班')),
            ],
            options={
                'verbose_name_plural': '教学任务书',
            },
        ),
        migrations.CreateModel(
            name='jiaoxuejindu_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhuanye_jiaoxue_jindu_id', models.CharField(max_length=6, verbose_name='专业教学进度号')),
                ('xuenian_xueqi_hao', models.CharField(max_length=28, verbose_name='学年学期号')),
                ('course_name', models.CharField(max_length=20, verbose_name='课程名')),
                ('xueshi_nums', models.CharField(max_length=20, verbose_name='学时数')),
                ('start_end_weeks', models.CharField(max_length=20, verbose_name='起始周')),
                ('weeks_times', models.CharField(max_length=4, verbose_name='周学时')),
                ('zhuanyehao', models.CharField(max_length=6, verbose_name='专业号')),
            ],
            options={
                'verbose_name_plural': '教学进度表',
            },
        ),
        migrations.CreateModel(
            name='ke_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=6, verbose_name='教师号')),
                ('shiduan', models.CharField(max_length=4, verbose_name='时段')),
                ('heban_hao', models.CharField(max_length=6, verbose_name='合班')),
                ('kecheng', models.CharField(max_length=6, verbose_name='课程')),
                ('jiaoshi', models.CharField(max_length=6, verbose_name='教室')),
                ('teacher', models.CharField(max_length=10, verbose_name='教师')),
            ],
        ),
        migrations.CreateModel(
            name='major_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhuanyehao_id', models.CharField(max_length=6, verbose_name='专业号')),
                ('zhuanye_name', models.CharField(max_length=28, verbose_name='专业名称')),
                ('college', models.CharField(max_length=20, verbose_name='学院')),
                ('people', models.CharField(max_length=8)),
                ('year', models.CharField(max_length=6)),
                ('hebanhao', models.CharField(max_length=6, verbose_name='合班号')),
                ('zhuanyehao', models.CharField(max_length=6, verbose_name='专业号')),
            ],
            options={
                'verbose_name_plural': '专业表',
            },
        ),
        migrations.CreateModel(
            name='shiyongqingkuang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syqk_id', models.CharField(max_length=6, verbose_name='使用情况号')),
                ('syqk_class', models.CharField(max_length=8, verbose_name='使用班级')),
                ('shiyongtime', models.CharField(max_length=8, verbose_name='使用')),
                ('shiyong_bool', models.CharField(max_length=4, verbose_name='使用与否')),
            ],
            options={
                'verbose_name_plural': '使用情况表',
            },
        ),
        migrations.CreateModel(
            name='teacher_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_hao', models.CharField(max_length=6, verbose_name='教师号')),
                ('xueyuan', models.CharField(max_length=28, verbose_name='学院')),
                ('zhicheng', models.CharField(max_length=28, verbose_name='职称')),
                ('name', models.CharField(max_length=28, verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '学期表',
            },
        ),
        migrations.CreateModel(
            name='xueqi_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuenian_xueqi_hao', models.CharField(max_length=28, verbose_name='学年学期号')),
                ('ruxue_xuenian', models.CharField(max_length=28, verbose_name='入学学年')),
                ('xueqi', models.CharField(max_length=28, verbose_name='学期')),
            ],
            options={
                'verbose_name_plural': '学年学期表',
            },
        ),
        migrations.CreateModel(
            name='xueyuan_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xueyuan_hao', models.CharField(max_length=6, verbose_name='学院号')),
                ('xueyuan_name', models.CharField(max_length=20, verbose_name='学院名')),
                ('tel', models.CharField(max_length=12, verbose_name='电话')),
            ],
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name_plural': '回复'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '回复', 'verbose_name_plural': '问题'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(max_length=2000, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Question', verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='图片内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='问题'),
        ),
    ]
